# site settings
title: "Steven Voon | XR Architect & Technical Lead"
email: voonyewsoon@gmail.com
description: "Consultant for Digitalization, XR Storytelling, and Spatial R&D"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stevenvoon.github.io"

author: Steven Voon
street_address: Selangor # Keep it general for privacy
city: Petaling Jaya
state: Selangor
zip_code: 47110
country: Malaysia
phone: 012-5652372

# homepage tiles
tiles-source: pages 
tiles-count: 4 # We only want our 4 Strategic Pillars showing on the home grid

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/stevenvoon
  LinkedIn: https://www.linkedin.com/in/steven-voon # Update this to your link
  #Instagram:
  #Facebook:

# CUSTOM COLLECTIONS (The "Secret Sauce")
# This tells Jekyll to look into your _projects and _lab folders
collections:
  projects:
    output: true
    permalink: /projects/:path/
  lab:
    output: true
    permalink: /lab/:path/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- vendor